spring.application.name=web-chat

spring.jpa.hibernate.ddl-auto=update

# database.properties
spring.datasource.url=jdbc:postgresql://localhost:5432/webchat
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.repositories.enabled=false

redis.host-name=${REDIS_HOSTNAME}
redis.port=${REDIS_PORT}
redis.username=${REDIS_USERNAME}
redis.password=${REDIS_PASSWORD}

# file-size.properties
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# jwt.properties
jwt.access-secret=${JWT_ACCESS_SECRET}
jwt.access-expiration-min=20

jwt.refresh-secret=${JWT_REFRESH_SECRET}
jwt.refresh-expiration-min=4320
